apiVersion: dapr.io/v1alpha1
kind: Component
metadata:
  name: baristapubsub
spec:
  type: pubsub.azure.servicebus
  version: v1
  metadata:
  - name: connectionString
    secretKeyRef:
      name: servicebus
      key: connectionString