apiVersion: keda.sh/v1alpha1
kind: ScaledObject
metadata:
  name: azure-servicebus-queue-scaledobject-counter
  namespace: default
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: counterservice
  minReplicaCount: 1
  triggers:
  - type: azure-servicebus
    metadata:
      namespace: coffeeshop-6btxmgewt7xsu
      topicName: orderup
      subscriptionName: counterservice
      messageCount: "5"
      connectionFromEnv: SERVICEBUS_CONNECTIONSTRING